import type { ServicePage } from "./services";

export const iugisServices: ServicePage[] = [
  {
    slug: "status-pedido-whatsapp",
    title: "Status de Pedido pelo WhatsApp",
    shortTitle: "Status de Pedido",
    keyword: "status de pedido WhatsApp",
    icon: "plug",
    image: "/images/iugis-one-platform-transparent.webp",
    description: "Atualizações proativas de rastreio e status do pedido pelo WhatsApp para reduzir contatos repetitivos e dar segurança ao cliente.",
    answer: "A automação de status de pedido da Iugis conecta eventos de envio e entrega ao WhatsApp. O cliente recebe informações no momento certo, enquanto seu time reduz chamados sobre rastreio e acompanha exceções com mais contexto.",
    problem: "Clientes sem visibilidade do pedido acionam o atendimento repetidamente, aumentando o custo operacional e a ansiedade após a compra.",
    solution: "Desenhamos mensagens transacionais claras, gatilhos de atualização e encaminhamento humano para exceções que exigem atenção.",
    deliverables: [
      "Mapeamento dos eventos de pedido e entrega",
      "Fluxos de atualização proativa no WhatsApp",
      "Mensagens de rastreio com linguagem da marca",
      "Tratamento de exceções e transferência para atendente",
      "Métricas de contatos evitados e resposta do cliente",
    ],
    process: [
      { title: "Mapeamento", description: "Identificamos eventos, transportadoras e dúvidas recorrentes." },
      { title: "Fluxos", description: "Criamos as mensagens e regras de cada etapa do pedido." },
      { title: "Integração", description: "Conectamos os eventos da operação à Iugis." },
      { title: "Otimização", description: "Acompanhamos exceções e refinamos a comunicação." },
    ],
    results: [
      "Menos tickets sobre rastreio e entrega",
      "Cliente mais seguro no pós-compra",
      "Atendimento focado em casos que exigem ação humana",
    ],
    forWho: [
      "Lojas com alto volume de dúvidas sobre pedido",
      "Operações que querem melhorar o pós-compra",
      "Times que já usam WhatsApp como canal de atendimento",
    ],
    notFor: ["Operações sem eventos confiáveis de pedido ou entrega disponíveis para integração"],
    faqs: [
      { question: "A Iugis envia o código de rastreio?", answer: "Sim, quando o dado estiver disponível na integração. O fluxo pode incluir link de acompanhamento e atualizações por etapa." },
    ],
  },
  {
    slug: "recuperacao-carrinho-whatsapp",
    title: "Recuperação de Carrinho pelo WhatsApp",
    shortTitle: "Recuperação de Carrinho",
    keyword: "recuperação de carrinho WhatsApp",
    icon: "plug",
    image: "/images/chat-v2.jpg",
    description: "Fluxos automatizados para recuperar carrinhos abandonados no WhatsApp com contexto do produto, timing adequado e atendimento quando necessário.",
    answer: "A Iugis transforma abandono em uma conversa útil: identifica o carrinho elegível, envia lembretes com contexto e direciona o shopper para concluir a compra ou tirar dúvidas. A estratégia respeita o momento da jornada, sem disparos genéricos.",
    problem: "Carrinhos abandonados representam receita perdida e campanhas pouco segmentadas tendem a gerar baixa resposta ou desgaste da base.",
    solution: "Combinamos gatilhos, segmentação e mensagens conversacionais para recuperar intenção de compra e levar casos complexos ao atendimento humano.",
    deliverables: [
      "Definição de gatilhos e janelas de recuperação",
      "Segmentação por carrinho, valor e comportamento",
      "Mensagens conversacionais com link de retorno",
      "Encaminhamento para especialista quando há dúvida",
      "Painel de acompanhamento de recuperação",
    ],
    process: [
      { title: "Diagnóstico", description: "Analisamos abandono, catálogo e oportunidades de recuperação." },
      { title: "Estratégia", description: "Definimos públicos, timing e mensagens por cenário." },
      { title: "Automação", description: "Configuramos os fluxos e links de retorno ao carrinho." },
      { title: "Aprendizado", description: "Medimos conversão e evoluímos o que gera resultado." },
    ],
    results: [
      "Mais oportunidades de conversão após o abandono",
      "Mensagens mais relevantes para cada shopper",
      "Visão clara da receita influenciada pelo WhatsApp",
    ],
    forWho: [
      "E-commerces com volume recorrente de carrinhos abandonados",
      "Marcas que buscam vender com atendimento consultivo",
      "Times que querem medir a automação além do disparo",
    ],
    notFor: ["Operações sem consentimento ou base elegível para comunicação pelo WhatsApp"],
    faqs: [
      { question: "A recuperação funciona para qualquer plataforma?", answer: "Avaliamos os eventos e dados disponíveis na sua plataforma para desenhar uma integração viável e mensurável." },
    ],
  },
  {
    slug: "integracoes-ecommerce",
    title: "Integrações Iugis para E-commerce",
    shortTitle: "Integrações Iugis",
    keyword: "integrações Iugis e-commerce WhatsApp API",
    icon: "plug",
    image: "/images/iugis-integracoes.png",
    description: "Conecte sua loja, ERP ou sistema proprietário à Iugis para sincronizar pedidos, status, catálogo e oportunidades de recuperação no WhatsApp.",
    answer: "As integrações Iugis conectam o que acontece na sua operação às conversas certas no WhatsApp. A plataforma pode receber eventos de pedido e abandono, consultar catálogo e acompanhar atualizações de status para que automações e atendimento atuem com informações atuais.",
    problem: "Quando e-commerce, ERP, atendimento e marketing trabalham isolados, o time perde contexto, responde tarde e deixa oportunidades de venda ou pós-compra passarem.",
    solution: "Mapeamos os dados e eventos relevantes, configuramos conectividade nativa, plugin ou API e validamos os fluxos que sustentam atendimento, rastreio e recuperação.",
    deliverables: [
      "Mapeamento de pedidos, catálogo, status e eventos críticos",
      "Conexão com plataformas de e-commerce e sistemas parceiros",
      "Sincronização de status para mensagens transacionais",
      "Integração de catálogo para conversas mais contextualizadas",
      "API e webhooks para cenários proprietários ou legados",
      "Testes, monitoramento e documentação da integração",
    ],
    process: [
      { title: "Diagnóstico técnico", description: "Identificamos sistemas, dados disponíveis e fluxos prioritários." },
      { title: "Arquitetura", description: "Definimos conexão nativa, plugin, API ou webhook para cada cenário." },
      { title: "Implementação", description: "Configuramos a troca de dados, regras de erro e validação ponta a ponta." },
      { title: "Operação", description: "Monitoramos eventos e evoluímos os fluxos conforme a operação cresce." },
    ],
    results: [
      "Dados mais atuais para automações e atendimento",
      "Menos trabalho manual entre sistemas",
      "Base conectada para recuperação, rastreio e conversas com contexto",
    ],
    forWho: [
      "Operações com e-commerce, ERP ou CRM que precisam conversar entre si",
      "Lojas que querem usar eventos de pedido e catálogo no WhatsApp",
      "Empresas com sistema proprietário ou integrações fora do padrão",
    ],
    notFor: ["Projetos sem acesso técnico, dados de origem ou responsável pelos sistemas envolvidos"],
    faqs: [
      { question: "Quais plataformas podem integrar com a Iugis?", answer: "A Iugis oferece conectividade para plataformas de e-commerce e também API e webhooks para cenários proprietários. Avaliamos o seu ecossistema antes de definir o melhor caminho." },
      { question: "É possível integrar um ERP legado?", answer: "Sim. Quando não há uma conexão pronta, avaliamos a API disponível, webhooks ou uma integração sob medida para sincronizar os eventos necessários." },
    ],
  },
];
